version: '3.1'

services:
  fastapi:
    container_name: fastapi_server
    build:
      context: .
    volumes:
      - ./app:/app
    ports:
      - 8001:8001
    command: uvicorn main:app --host 0.0.0.0 --port 8001 --reload